[package]
name = "francisco-perez-sorrosal/nxs"
version = "0.0.1"
description = "Nexus app"
readme = "README.md"

[dependencies]
"wasmer/python" = "^3.12.9"

[fs]
"/src" = "./src"
"/cpython/lib/python3.12" = "./.venv/lib/python3.12"

[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-m", "nxs"]
env = ["PYTHONEXECUTABLE=./venv/bin/python", "PYTHONPATH=./src"]
